version: '3.3'

services:
  qute-blog-mysql:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: vs4tw
      MYSQL_DATABASE: qute-blog
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser

  qute-blog:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 80:8080
    depends_on:
      - qute-blog-mysql